paths:
  /api/products/:
    get:
      summary: Shows all the products charged in the db
      tags: 
        - Products
      responses:
        '200':
          description: All products info obtained successfully
        '500':
          description: Internal error server
    post: 
      summary: Creates a new product
      tags: 
        - Products
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Product'
      responses:
        '201':
          description: Product created in a successful manner
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '500':
          description: Internal error server
  /api/products/{pid}:
    get:
      summary: Finds ONE product by Id
      tags:
        - Products
      parameters:
        name: pid
        in: path
        required: true
        description: Searched product id
        schema:
          $type: String
      responses:
        '200':
          description: Product obtained successfully
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal error server
    put:
      summary: Updates an user searched by its ID
      tags:
       - Products
      parameters:
        name: pid
        in: path
        required: true
        description: Id of the product to update
        schema: 
          type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/reqBodies/updateProd'
    delete:
      summary: Deletes the product which id was specified
      tags:
        - Products
      parameters:
        name: pid
        in: path
        required: true
        description: Id of the product to delete
      responses:
        '200':
          description: Product removed in a successful manner
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '500':
          description: Internal error server

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID generated by Mongo
        title:
          type: String
          description: Product's name
        price:
          type: Number
          description: Product's price
        description:
          type: String
          description: Some details about the product
        category: 
          type: String
          description: Category to which the object belongs
        code:
          type: Number
          description: Product's number code
        stock:
          type: Number
          description: Number of items of one product available
        owner: 
          type: String
          description: Id of the person who created this product
        thumbnail:
          type: Array
          description: Product's image
      example: 
        _id: ObjectId("64a36f59b962882be13f2f97")
        title: Apple iPhone 14
        description: Built and designed by Apple Inc.
        price: 315000
        category: smartphone
        code: 101
        stock: 51
        owner: admin
        thumbnail: []
  reqBodies:
    updateProd:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID generated by Mongo
        title:
          type: String
          description: Product's name
        price:
          type: Number
          description: Product's price
        description:
          type: String
          description: Some details about the product
        category: 
          type: String
          description: Category to which the object belongs
        code:
          type: Number
          description: Product's number code
        stock:
          type: Number
          description: Number of items of one product available
        owner: 
          type: String
          description: Id of the person who created this product
        thumbnail:
          type: Array
          description: Product's image
      example:
        _id: ObjectId("64a36f59b962882be13f2f97")
        title: Apple iPhone 14
        description: Built and designed by Apple Inc.
        price: 315000
        category: smartphone
        code: 101
        stock: 51
        owner: admin
        thumbnail: []
